[package]
name = "resvg"
version = "0.5.0"
authors = ["Evgeniy Reizner <razrfalcon@gmail.com>"]
keywords = ["svg", "render", "raster"]
license = "MPL-2.0"
description = "An SVG rendering library."
documentation = "https://docs.rs/resvg/"
repository = "https://github.com/RazrFalcon/resvg"
readme = "README.md"
categories = ["multimedia::images"]

[workspace]
members = [
    "capi",
    "tools/rendersvg",
    "tools/usvg",
    "examples/cairo-rs",
    "usvg",
    "resvg-qt",
]

[badges]
travis-ci = { repository = "RazrFalcon/resvg" }

[dependencies]
font-kit = { git = "https://github.com/pcwalton/font-kit", rev = "159c016" }
harfbuzz_rs = { git = "https://github.com/manuel-rhdt/harfbuzz_rs", rev = "bc5c8bc" }
log = "0.4.5"
lyon_path = "0.12"
rgb = "0.8.9"
unicode-bidi = "0.3.4"
unicode-segmentation = "1.2.1" # TODO: reexport?
unicode-script = "0.2.0"
usvg = { path = "usvg", version = "0.5" }

# cairo backend
cairo-rs = { version = "0.5", features = ["png"], optional = true }
gdk-pixbuf = { version = "0.5", optional = true }

# qt backend
resvg-qt = { path = "resvg-qt", version = "0.5.0", optional = true }

[features]
cairo-backend = ["cairo-rs", "gdk-pixbuf"]
qt-backend = ["resvg-qt"]

[lib]
doctest = false

[profile.release]
lto = true
