[package]
name = "usvg"
# When updating version, also modify html_root_url in the lib.rs and in the ../tools/Cargo.toml
version = "0.5.0"
authors = ["Evgeniy Reizner <razrfalcon@gmail.com>"]
keywords = ["svg"]
license = "MPL-2.0"
description = "An SVG simplification library."
categories = ["multimedia::images"]
repository = "https://github.com/RazrFalcon/resvg"
documentation = "https://docs.rs/usvg/"
readme = "README.md"
exclude = ["testing_tools/**"]
workspace = ".."

[badges]
travis-ci = { repository = "RazrFalcon/resvg" }

[dependencies]
base64 = "0.10"
font-kit = { git = "https://github.com/pcwalton/font-kit", rev = "6c78ceb" }
harfbuzz_rs = "1.0"
libflate = "0.1"
log = "0.4"
lyon_geom = "0.12"
lyon_path = "0.12"
rctree = "0.2.1"
svgdom = "0.16"
unicode-bidi = "0.3.4"
unicode-script = "0.2.0"

[dev-dependencies]
pretty_assertions = "0.5.1"
